### ISSUE TITLE
composer cannot find package

### ISSUE THREAD

**Issue by rkingon** [onedesign/onelogger#2]
> [InvalidArgumentException]
  Could not find a matching version of package onedesign/onelogger. Check the package spelling, your ver
  sion constraint and that the package is available in a stability which matches your minimum-stability.

Composer throws an error when trying to install this plugin -- unable to find.

Thoughts?

**Comment by brianjhanson** [comment]
Hey @rkingon,

What does your `composer.json` file look like? This package isn't currently published on packagist, so you have to make sure you add the repositories key to tell composer where to find it.

Something like:

```json
    "repositories": [
      {
        "type": "vcs",
        "url": "https://github.com/onedesign/onelogger"
      }
    ],
```

**Comment by rkingon** [comment]
I totally missed that part of the documentation!

My apologies. :)

**Comment by brianjhanson** [comment]
No worries! Hope the plugin does what you need it to.
